
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Test Product 2",
    "price": 100.55
}

### 

GET http://localhost:8000/products/840e6e8d-12c4-476b-af46-70c4b2c02a58	
Content-Type: application/json

### 

GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODI1NTMzODYsInN1YiI6ImNhNmEzYzhkLWI1MzUtNDI4My04MmYzLWEzNWI2NDhlYmFmMSJ9.8KwQr7NuR_xsSj0cpZ6DhnDU3mALPVQXCPP4H-gs8kY


###

PUT http://localhost:8000/products/840e6e8d-12c4-476b-af46-70c4b2c02a58	
Content-Type: application/json
{
    "name": "Test Product updated",
    "price": 200.50
}

###

DELETE  http://localhost:8000/products/840e6e8d-12c4-476b-af46-70c4b2c02a58	