basePath: /
host: localhost:8000
info:
  contact:
    email: gustascrows@gmail.com
    name: Luis Gustavo
    url: https://www.linkedin.com/in/godoyluisgustavo/
  description: This is a simple API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Expeet API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
